stages:
  clean:
    cmd: python clean.py
    deps:
    - clean.py
    - test.csv
    - train.csv
    params:
    - clean
    outs:
    - test.pickle
    - train.pickle
  train:
    cmd: python train.py
    deps:
    - train.pickle
    - train.py
    params:
    - train
    outs:
    - model
    metrics:
    - training_metrics.json:
        cache: false
    plots:
    - training_metrics/scalars:
        cache: false
  predict:
    cmd: python predict.py
    deps:
    - predict.py
    - test.pickle
    - sample_submission.csv
    - model
    params:
    - train
    outs:
    - submission.csv
